MODEL:
  NAME: "GPA2Cls-V1"
  ID: "gpa2cls-v1-r50-fl2"
  INTRO: "GPA2Cls-V1 w/ FocalLocator2"

BACKBONE:
  NAME: "ResNet-50"
  PRETRAINED: True
  PRETRAINED_FILE: "saved/resnet50-CUB-200.pth"
  STAGES: [0, 0, 0, 0, 1]

FOCAL_LOCATOR:
  NAME: "FocalLocator2"
  SIZE: 448
  STRIDE: 32
  FOCAL_SIZE: [256, 320, 384, 448]

SCALING_LAYER:
  NAME: "ScalingLayer"
  IN_CHANNELS: [2048]
  OUT_CHANNELS: [2048]
  TRANSPARENT: True

GLOBAL_PERCEPTION_ATTN_LAYER:
  NAME: "GlobalPerceptionAttentionLayer"
  IN_CHANNELS: [2048]
  SPLIT_SIZES: [1]
  SE_DESIGNS: ['se']
  TRANSPARENT: True

CLASSIFIER:
  NAME: "Classifier"
  IN_FEATURES: [2048, 2048]
  NUM_CLASSES: 200
  POOLING: 'avg'
  DROPOUT: True
